// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn3-GKYKBNDAYpQxPB8ZfvkSrAdX3s1fs',
    appId: '1:829582636632:web:b75bc75dbd8504a9613c2d',
    messagingSenderId: '829582636632',
    projectId: 'storeimage-e8a2c',
    authDomain: 'storeimage-e8a2c.firebaseapp.com',
    storageBucket: 'storeimage-e8a2c.appspot.com',
    measurementId: 'G-M5Y5GNLV01',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHkDw38YKquDK5cziDdCvskTXTsk3xL30',
    appId: '1:829582636632:android:067d3cd4552a11db613c2d',
    messagingSenderId: '829582636632',
    projectId: 'storeimage-e8a2c',
    storageBucket: 'storeimage-e8a2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuJAo9LXm5FYLIuDXADtXvye0rP3sq6FM',
    appId: '1:829582636632:ios:c1a2699ad3734fa6613c2d',
    messagingSenderId: '829582636632',
    projectId: 'storeimage-e8a2c',
    storageBucket: 'storeimage-e8a2c.appspot.com',
    iosBundleId: 'com.example.storeimage1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuJAo9LXm5FYLIuDXADtXvye0rP3sq6FM',
    appId: '1:829582636632:ios:043bc3f87d444363613c2d',
    messagingSenderId: '829582636632',
    projectId: 'storeimage-e8a2c',
    storageBucket: 'storeimage-e8a2c.appspot.com',
    iosBundleId: 'com.example.storeimage1.RunnerTests',
  );
}
